# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 862)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SearchTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.SearchTableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.SearchTableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SearchTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.SearchTableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.SearchTableWidget.setObjectName("SearchTableWidget")
        self.SearchTableWidget.setColumnCount(0)
        self.SearchTableWidget.setRowCount(0)
        self.SearchTableWidget.horizontalHeader().setVisible(False)
        self.SearchTableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.SearchTableWidget)
        self.SearchPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchPushButton.sizePolicy().hasHeightForWidth())
        self.SearchPushButton.setSizePolicy(sizePolicy)
        self.SearchPushButton.setObjectName("SearchPushButton")
        self.horizontalLayout.addWidget(self.SearchPushButton)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FilterLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.FilterLineEdit.setObjectName("FilterLineEdit")
        self.verticalLayout_2.addWidget(self.FilterLineEdit)
        self.StockListWidget = QtWidgets.QListWidget(self.groupBox)
        self.StockListWidget.setModelColumn(0)
        self.StockListWidget.setObjectName("StockListWidget")
        self.verticalLayout_2.addWidget(self.StockListWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 6)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 8)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 21))
        self.menubar.setObjectName("menubar")
        self.menuParament_List = QtWidgets.QMenu(self.menubar)
        self.menuParament_List.setObjectName("menuParament_List")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPE = QtWidgets.QAction(MainWindow)
        self.actionPE.setCheckable(True)
        self.actionPE.setChecked(True)
        self.actionPE.setObjectName("actionPE")
        self.actionPB = QtWidgets.QAction(MainWindow)
        self.actionPB.setCheckable(True)
        self.actionPB.setChecked(True)
        self.actionPB.setObjectName("actionPB")
        self.actionTime = QtWidgets.QAction(MainWindow)
        self.actionTime.setCheckable(True)
        self.actionTime.setChecked(True)
        self.actionTime.setObjectName("actionTime")
        self.actiontotal = QtWidgets.QAction(MainWindow)
        self.actiontotal.setCheckable(True)
        self.actiontotal.setChecked(True)
        self.actiontotal.setObjectName("actiontotal")
        self.actionPrice = QtWidgets.QAction(MainWindow)
        self.actionPrice.setCheckable(True)
        self.actionPrice.setObjectName("actionPrice")
        self.actionindustry = QtWidgets.QAction(MainWindow)
        self.actionindustry.setCheckable(True)
        self.actionindustry.setObjectName("actionindustry")
        self.actionarea = QtWidgets.QAction(MainWindow)
        self.actionarea.setCheckable(True)
        self.actionarea.setObjectName("actionarea")
        self.actionoutstanding = QtWidgets.QAction(MainWindow)
        self.actionoutstanding.setCheckable(True)
        self.actionoutstanding.setObjectName("actionoutstanding")
        self.actiontotalAssets = QtWidgets.QAction(MainWindow)
        self.actiontotalAssets.setCheckable(True)
        self.actiontotalAssets.setObjectName("actiontotalAssets")
        self.actionliquidAssets = QtWidgets.QAction(MainWindow)
        self.actionliquidAssets.setCheckable(True)
        self.actionliquidAssets.setObjectName("actionliquidAssets")
        self.actionfixedAssets = QtWidgets.QAction(MainWindow)
        self.actionfixedAssets.setCheckable(True)
        self.actionfixedAssets.setObjectName("actionfixedAssets")
        self.actionreserved = QtWidgets.QAction(MainWindow)
        self.actionreserved.setCheckable(True)
        self.actionreserved.setObjectName("actionreserved")
        self.actionreservedPerShare = QtWidgets.QAction(MainWindow)
        self.actionreservedPerShare.setCheckable(True)
        self.actionreservedPerShare.setObjectName("actionreservedPerShare")
        self.actionesp = QtWidgets.QAction(MainWindow)
        self.actionesp.setCheckable(True)
        self.actionesp.setObjectName("actionesp")
        self.actiontimeToMarket = QtWidgets.QAction(MainWindow)
        self.actiontimeToMarket.setCheckable(True)
        self.actiontimeToMarket.setObjectName("actiontimeToMarket")
        self.actionundp = QtWidgets.QAction(MainWindow)
        self.actionundp.setCheckable(True)
        self.actionundp.setObjectName("actionundp")
        self.actionperundp = QtWidgets.QAction(MainWindow)
        self.actionperundp.setCheckable(True)
        self.actionperundp.setObjectName("actionperundp")
        self.actionrev = QtWidgets.QAction(MainWindow)
        self.actionrev.setCheckable(True)
        self.actionrev.setObjectName("actionrev")
        self.actionprofit = QtWidgets.QAction(MainWindow)
        self.actionprofit.setCheckable(True)
        self.actionprofit.setObjectName("actionprofit")
        self.actiongpr = QtWidgets.QAction(MainWindow)
        self.actiongpr.setCheckable(True)
        self.actiongpr.setObjectName("actiongpr")
        self.actionnpr = QtWidgets.QAction(MainWindow)
        self.actionnpr.setCheckable(True)
        self.actionnpr.setObjectName("actionnpr")
        self.actionholders = QtWidgets.QAction(MainWindow)
        self.actionholders.setCheckable(True)
        self.actionholders.setObjectName("actionholders")
        self.menuParament_List.addAction(self.actionPE)
        self.menuParament_List.addAction(self.actionPB)
        self.menuParament_List.addAction(self.actionTime)
        self.menuParament_List.addAction(self.actiontotal)
        self.menuParament_List.addAction(self.actionPrice)
        self.menuParament_List.addAction(self.actionindustry)
        self.menuParament_List.addAction(self.actionarea)
        self.menuParament_List.addAction(self.actionoutstanding)
        self.menuParament_List.addAction(self.actiontotalAssets)
        self.menuParament_List.addAction(self.actionliquidAssets)
        self.menuParament_List.addAction(self.actionfixedAssets)
        self.menuParament_List.addAction(self.actionreserved)
        self.menuParament_List.addAction(self.actionreservedPerShare)
        self.menuParament_List.addAction(self.actionesp)
        self.menuParament_List.addAction(self.actiontimeToMarket)
        self.menuParament_List.addAction(self.actionundp)
        self.menuParament_List.addAction(self.actionperundp)
        self.menuParament_List.addAction(self.actionrev)
        self.menuParament_List.addAction(self.actionprofit)
        self.menuParament_List.addAction(self.actiongpr)
        self.menuParament_List.addAction(self.actionnpr)
        self.menuParament_List.addAction(self.actionholders)
        self.menubar.addAction(self.menuParament_List.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "stock analysis"))
        self.SearchPushButton.setText(_translate("MainWindow", "Search"))
        self.groupBox_2.setTitle(_translate("MainWindow", "apple(11011)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "day"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "month"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "year"))
        self.menuParament_List.setTitle(_translate("MainWindow", "Add"))
        self.actionPE.setText(_translate("MainWindow", "PE"))
        self.actionPB.setText(_translate("MainWindow", "PB"))
        self.actionTime.setText(_translate("MainWindow", "Time"))
        self.actiontotal.setText(_translate("MainWindow", "totals"))
        self.actionPrice.setText(_translate("MainWindow", "Price"))
        self.actionindustry.setText(_translate("MainWindow", "industry"))
        self.actionarea.setText(_translate("MainWindow", "area"))
        self.actionoutstanding.setText(_translate("MainWindow", "outstanding"))
        self.actiontotalAssets.setText(_translate("MainWindow", "totalAssets"))
        self.actionliquidAssets.setText(_translate("MainWindow", "liquidAssets"))
        self.actionfixedAssets.setText(_translate("MainWindow", "fixedAssets"))
        self.actionreserved.setText(_translate("MainWindow", "reserved"))
        self.actionreservedPerShare.setText(_translate("MainWindow", "reservedPerShare"))
        self.actionesp.setText(_translate("MainWindow", "esp"))
        self.actiontimeToMarket.setText(_translate("MainWindow", "timeToMarket"))
        self.actionundp.setText(_translate("MainWindow", "undp"))
        self.actionperundp.setText(_translate("MainWindow", "perundp"))
        self.actionrev.setText(_translate("MainWindow", "rev"))
        self.actionprofit.setText(_translate("MainWindow", "profit"))
        self.actiongpr.setText(_translate("MainWindow", "gpr"))
        self.actionnpr.setText(_translate("MainWindow", "npr"))
        self.actionholders.setText(_translate("MainWindow", "holders"))

